apiVersion: v1
kind: Pod
metadata:
  name: wp-content-migrator
  namespace: wp
spec:
  containers:
  - name: migrator
    image: alpine
    command: ["/bin/sh", "-c", "sleep infinity"]
    volumeMounts:
    - name: old
      mountPath: /old
    - name: new
      mountPath: /new
  volumes:
  - name: old
    persistentVolumeClaim:
      claimName: wp-content
  - name: new
    persistentVolumeClaim:
      claimName: wp-content-rwx
  restartPolicy: Never