apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-content-rwx
  namespace: wp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi